<?php
	$content = array (
		array(
			'id_personnel' => 1, 
			'surname' => 'Бородина', 
			'name' => 'Ксения', 
			'patronymic' => 'Алексеевна', 
			'post' => 'Преподаватель', 
			'main_post' => '', 
			'category' => 'Соответствие занимаемой должности', 
			'level_edu' => 'Высшее профессиональное ', 
			'experience_total' => 21.3, 
			'experience_college' => 14.5, 
			'email' => '', 
			'site' => '', 
			'unit' => 'Преподаватели', 
			'note' => '', 
			'actual' => 1, 
			'hidden' => 0
		),
		array(
			'id_personnel' => 2, 
			'surname' => 'Кошкова', 
			'name' => 'Вера', 
			'patronymic' => 'Николаевна', 
			'post' => 'Преподаватель', 
			'main_post' => '', 
			'category' => 'Соответствие занимаемой должности', 
			'level_edu' => 'Высшее профессиональное ', 
			'experience_total' => 29.1, 
			'experience_college' => 29.1, 
			'email' => 'koshkova_v_n@mail.ru', 
			'site' => '', 
			'unit' => 'Преподаватели', 
			'note' => '', 
			'actual' => 1, 
			'hidden' => 0
		),
		array(
			'id_personnel' => 3, 
			'surname' => 'Рыбкина', 
			'name' => 'Ольга', 
			'patronymic' => 'Витальевна', 
			'post' => 'Преподаватель', 
			'main_post' => '', 
			'category' => 'Соответствие занимаемой должности', 
			'level_edu' => 'Высшее профессиональное ', 
			'experience_total' => 21.3, 
			'experience_college' => 14.5, 
			'email' => 'RubkinaOlga1234@mail.ru', 
			'site' => '', 
			'unit' => 'Преподаватели', 
			'note' => '', 
			'actual' => 1, 
			'hidden' => 0
		),		
		array(
			'id_personnel' => 4, 
			'surname' => 'Маркова', 
			'name' => 'Елизавета', 
			'patronymic' => 'Андреевна', 
			'post' => 'Преподаватель', 
			'main_post' => '', 
			'category' => 'Первая', 
			'level_edu' => 'Высшее профессиональное ', 
			'experience_total' => 19.11, 
			'experience_college' => 16.5, 
			'email' => 'markovaaa.el@gmail.com', 
			'site' => '', 
			'unit' => 'Преподаватели', 
			'note' => '', 
			'actual' => 1, 
			'hidden' => 0
		),
		array(
			'id_personnel' => 5, 
			'surname' => 'Ильчук', 
			'name' => 'Виталина', 
			'patronymic' => 'Георгиевна', 
			'post' => 'Преподаватель', 
			'main_post' => 'Заведующий по профессиям', 
			'category' => 'Высшая', 
			'level_edu' => 'Высшее профессиональное ', 
			'experience_total' => 36.1, 
			'experience_college' => 19, 
			'email' => 'il4uk.v@mail.ru', 
			'site' => 'iamil4uk.ru', 
			'unit' => 'Преподаватели', 
			'note' => '', 
			'actual' => 1, 
			'hidden' => 0
		)				
	)
?>